#Set REMOTE_BROWSER_PLATFROM TO BS TO RUN ON BROWSERSTACK else
#SET REMOTE_BROWSER_PLATFORM TO SL TO RUN ON SAUCE LABS
REMOTE_BROWSER_PLATFORM = "BS"


USERNAME = "ganesh476"
ACCESS_KEY = "JrTbqPnBHEdJ1hfGiZVW"

